export enum MatchTypeLottery {
  $7_RAKAM = '$7_RAKAM',
  $6_RAKAM = '$6_RAKAM',
  SON_ALTI_RAKAM = 'SON_ALTI_RAKAM',
  SON_BES_RAKAM = 'SON_BES_RAKAM',
  SON_DORT_RAKAM = 'SON_DORT_RAKAM',
  SON_UC_RAKAM = 'SON_UC_RAKAM',
  SON_IKI_RAKAM = 'SON_IKI_RAKAM',
  AMORTI = 'AMORTI',
  TESELLI = 'TESELLI',
}
