export enum MatchTypeRegular {
  $HIC = '$HIC',
  $1_1_BILEN = '$1_1_BILEN',
  $2_1_BILEN = '$2_1_BILEN',
  $3_1_BILEN = '$3_1_BILEN',
  $4_1_BILEN = '$4_1_BILEN',
  $5_1_BILEN = '$5_1_BILEN',
  $3_BILEN = '$3_BILEN',
  $4_BILEN = '$4_BILEN',
  $5_BILEN = '$5_BILEN',
  $6_BILEN = '$6_BILEN',
  $7_BILEN = '$7_BILEN',
  $8_BILEN = '$8_BILEN',
  $9_BILEN = '$9_BILEN',
  $10_BILEN = '$10_BILEN',
}
